### ISSUE TITLE
Поправки по плану

### ISSUE THREAD

**Issue by ArRomanov** [VEAlekseev/Diploma#1]
## Сценарии
По одной из карт (4442) у вас должны быть отказы по покупкам, потому что у нее статус **DECLINED**.

## Инструменты
Intellij IDEA - полное название среды разработки
Allure написали два раза

## Риски
В общем ок, только **Сложности в работе с БД и docker** лучше заменить на **Сложности в настройки инфраструктуры**, а **Сложности в корректном запуске SUT.** на **Сложности в настройке запуска SUT с различными параметрами.**

## Оценка
Хорошо описана оценка, но лучше убрать интервальные оценки. Вместо интервалов принято указывать время, заложенное на риски, это порядка 15-25%, поэтому лучше написать оптимальную оценку и рядом дописать время на непредвиденные ситуации и в итоге получите некий интервал. Ну и часто оценку пишут не просто в часах/днях, а в человеко-часах/человеко-днях.

## Сдача работ
Количество дней не совсем совпадает с вашей оценкой. Постарайтесь откорректировать оценку или план сдачи, чтобы ваша оценка укладывалась в интервалах плана сдачи

В общем, план хороший. Думаю, изменения в дальнейшем будут минимальные.

**Comment by VEAlekseev** [comment]
Внес правки в план.

**Comment by ArRomanov** [comment]
Перенесите сценарии с картой, по которой будут отказаны покупки, в позитивные сценарии. У нас изначально карта подготовлена именно под этот сценарий, то есть это одни из основных сценариев. Когда поправите, можно просто закрыть ишью.
